### ISSUE TITLE
Figure out how to generate rules.yaml

### ISSUE THREAD

**Issue by unordered-set** [ValiDAO/sergen#1]
At the moment we have alerts_rules file which is written manually. It contains things like:

```
cat alert_rules.yml

groups:
- name: example_alerting_group
  rules:
  - alert: Agoric is slow
    expr: rate(tendermint_consensus_latest_block_height{job="agoric"}[5m]) < 0.1
    for: 1s
    labels:
      severity: page
    annotations:
      summary: Agoric does not produce blocks

  - alert: Agoric is down
    expr: up{job="agoric"} == 0.0
    for: 1s
    labels:
      severity: page
    annotations:
      summary: Agoric is down

  - alert: Solana high skiprate
    expr: solana_skiprate{job="solana"} > 0.35 and solana_leader_slots{job="solana"} > 12
    for: 1s
    labels:
      severity: page
    annotations:
      summary: Solana high skiprate
```

etc.

Aim is to expand some agreement about folder structure so such a file can be generated automatically + prometheus is restarted after each regenration
